services:
  - type: web
    name: HMA
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7