"""add_hostel_approval_fields

Revision ID: 74d1eaf47673
Revises: 3e506702cd37
Create Date: 2026-07-10 10:30:14.730916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_hostel_approval_fields

Revision ID: 74d1eaf47673
Revises: 3e506702cd37
Create Date: 2026-07-10 10:30:14.730916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d1eaf47673'
down_revision: Union[str, Sequence[str], None] = '3e506702cd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Execute raw SQL to add enum value to PostgreSQL enum type
    # Use op.get_bind().dialect.name to check if it is postgresql
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        # ALTER TYPE cannot run inside a transaction block in some postgres versions
        # so we run it with autocommit context if possible, or try-catch
        try:
            op.execute("COMMIT")  # Commit current transaction to allow ALTER TYPE
            op.execute("ALTER TYPE hostelstatus ADD VALUE 'changes_requested'")
        except Exception:
            # If it fails (e.g. value already exists), ignore it
            pass

    op.add_column('hostels', sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('hostels', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('hostels', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('hostels', sa.Column('document_url', sa.String(length=500), nullable=True))
    op.add_column('hostels', sa.Column('document_type', sa.String(length=100), nullable=True))
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostels', 'document_type')
    op.drop_column('hostels', 'document_url')
    op.drop_column('hostels', 'status_reason')
    op.drop_column('hostels', 'is_verified')
    op.drop_column('hostels', 'is_active')
    # ### end Alembic commands ###
