"""enforce 1 to 1 mapping for supervisor and hostel

Revision ID: aa24b30974b0
Revises: d4e5f6a7b8c9
Create Date: 2026-07-23 10:31:33.911106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa24b30974b0'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervisor_hostel_mappings_hostel_id'), table_name='supervisor_hostel_mappings')
    op.create_index(op.f('ix_supervisor_hostel_mappings_hostel_id'), 'supervisor_hostel_mappings', ['hostel_id'], unique=True)
    op.drop_index(op.f('ix_supervisor_hostel_mappings_supervisor_id'), table_name='supervisor_hostel_mappings')
    op.create_index(op.f('ix_supervisor_hostel_mappings_supervisor_id'), 'supervisor_hostel_mappings', ['supervisor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervisor_hostel_mappings_supervisor_id'), table_name='supervisor_hostel_mappings')
    op.create_index(op.f('ix_supervisor_hostel_mappings_supervisor_id'), 'supervisor_hostel_mappings', ['supervisor_id'], unique=False)
    op.drop_index(op.f('ix_supervisor_hostel_mappings_hostel_id'), table_name='supervisor_hostel_mappings')
    op.create_index(op.f('ix_supervisor_hostel_mappings_hostel_id'), 'supervisor_hostel_mappings', ['hostel_id'], unique=False)
    # ### end Alembic commands ###
